In [1]:
import uos_statphys

In [3]:
a = uos_statphys.IsingModel()
a.add_set(10,2,10,100)

In [6]:
a.simulate(10)

100%|██████████| 1/1 [00:00<00:00, 125.83it/s]


In [8]:
a.get_analyzer()

In [5]:
import os, pathlib
pathlib.Path(os.curdir

TypeError: 'PosixPath' object is not subscriptable

In [8]:
import uos_statphys

AttributeError: /mnt/c/Users/Jeong/master/uos_statphys/uos_statphys/lib/isingmonte.so: undefined symbol: monteCarlo

In [7]:
import uos_statphys.C_ext

AttributeError: /mnt/c/Users/Jeong/master/uos_statphys/uos_statphys/lib/isingmonte.so: undefined symbol: monteCarlo

In [5]:
C_ext.internal_Library('isingmonte')

NameError: name 'C_ext' is not defined

In [5]:
a = C_ext.from_C_source('uos_statphys/lib/src/isingmonte.cpp', r'-I /mnt/c/Users/Jeong/master/uos_statphys/uos_statphys/lib/src',debug=True) 

C functions found from source : 
	set_seed
	nearest_neighbor
	MCstep
	single_monteCarlo
	thread_monteCarlo
	monteCarlo
	MCwolff
	single_wolff
	thread_wolff
	wolff
Compile : g++ -o __libisingmonte.so __temp__isingmonte.cpp -shared -fPIC -I /mnt/c/Users/Jeong/master/uos_statphys/uos_statphys/lib/src


In [6]:
import numpy as np

In [3]:
import os

In [6]:
import ctypes

In [ ]:
ctypes.windll.kernel32.

In [10]:
ctypes.CDLL("libdl.dll")

OSError: [WinError 126] 지정된 모듈을 찾을 수 없습니다

In [6]:
import subprocess

In [18]:
print(subprocess.run(r"g++ -o __libisingmonte.so __temp__isingmonte.cpp -shared -fPIC -I /mnt/c/Users/Jeong/master/uos_statphys/uos_statphys/lib/src".split(), capture_output=True))

CompletedProcess(args=['g++', '-o', '__libisingmonte.so', '__temp__isingmonte.cpp', '-shared', '-fPIC', '-I', '/mnt/c/Users/Jeong/master/uos_statphys/uos_statphys/lib/src'], returncode=0, stdout=b'', stderr=b'In file included from /mnt/c/Users/Jeong/master/uos_statphys/uos_statphys/lib/src/dSFMT-params.h:4,\n                 from /mnt/c/Users/Jeong/master/uos_statphys/uos_statphys/lib/src/dSFMT.c:18,\n                 from __temp__isingmonte.cpp:1:\n/mnt/c/Users/Jeong/master/uos_statphys/uos_statphys/lib/src/dSFMT.h:46:4: warning: #warning "DSFMT_MEXP is not defined. I assume DSFMT_MEXP is 19937." [-Wcpp]\n   46 |   #warning "DSFMT_MEXP is not defined. I assume DSFMT_MEXP is 19937."\n      |    ^~~~~~~\n')


In [10]:
import sys, os

In [20]:
os.environ['C_INCLUDE_PATH'] = r"C:\Users\Jeong\master\uos_statphys\uos_statphys\src"

In [3]:
sys.path

['c:\\Users\\Jeong\\master\\uos_statphys',
 'c:\\Users\\Jeong\\.vscode\\extensions\\ms-toolsai.jupyter-2020.12.414227025\\pythonFiles\\vscode_datascience_helpers\\..\\.does-not-exist',
 'c:\\Users\\Jeong\\.vscode\\extensions\\ms-toolsai.jupyter-2020.12.414227025\\pythonFiles',
 'c:\\Users\\Jeong\\.vscode\\extensions\\ms-toolsai.jupyter-2020.12.414227025\\pythonFiles\\lib\\python',
 'C:\\Users\\Jeong\\Anaconda3\\python37.zip',
 'C:\\Users\\Jeong\\Anaconda3\\DLLs',
 'C:\\Users\\Jeong\\Anaconda3\\lib',
 'C:\\Users\\Jeong\\Anaconda3',
 '',
 'C:\\Users\\Jeong\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\Jeong\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Jeong\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Jeong\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Jeong\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Jeong\\.ipython',
 'c:\\Users\\Jeong\\master\\uos_statphys\\src\\origin']

In [2]:
cdll = C_ext.from_C_source("uos_statphys/src/origin/isingmonte.cpp", '-O2', '-Wall', '-Lmkl', debug=True)

C functions found from source : 
	set_seed
	nearest_neighbor
	MCstep
	single_monteCarlo
	thread_monteCarlo
	monteCarlo
	MCwolff
	single_wolff
	thread_wolff
	wolff
Compile : clang -o __libisingmonte.dll __temp__isingmonte.cpp -shared -O2 -Wall -Lmkl


In [3]:
import ctypes

In [4]:
a = 1 
b = ctypes.c_int(a)

In [7]:
import numpy as np

In [8]:
a = np.empty([2])

In [9]:
ctypes.byref(a)

TypeError: byref() argument must be a ctypes instance, not 'numpy.ndarray'

In [2]:
cdll = C_ext.from_C_source("scons/test.cpp", '-O2', '-Wall', '-Lmkl', debug=True)

C functions found from source : 
	add
	array_add
	dot_product
	fibonacci_array
Compile : clang -o __libtest.dll __temp__test.cpp -shared -O2 -Wall -Lmkl


In [3]:
del cdll

Exception ignored in: <function C_functions.__del__ at 0x000002769F21D798>
Traceback (most recent call last):
  File "c:\Users\Jeong\master\uos_statphys\uos_statphys\C_ext\__init__.py", line 60, in __del__
    os.remove(self._path)
PermissionError: [WinError 5] 액세스가 거부되었습니다: './__libtest.dll'


In [4]:
import numpy as np

In [5]:
size = 10
a = np.zeros([size], dtype = np.int32)
cdll.fibonacci_array(a, size)

In [3]:
cdll.close()

NameError: name 'cdll' is not defined

In [3]:
a, b = None, None

In [10]:
from talert import talert

In [11]:
with talert("test"):
    print("done")

done


In [36]:
cdefs = """
int test(
    int a,
    int b,
    int c,
    int* testest
){
    return 0;
}
"""

In [37]:
llllll = cdefs.split("\n")

In [38]:
i = 1
line = llllll[i]
funcdef = ""
if "(" in line:
    while not ")" in line:
        funcdef+= line#[:-1]
        i+=1
        line = llllll[i]
    funcdef+= line#[:-1]

In [39]:
funcdef

'int test(    int a,    int b,    int c,    int* testest){'

In [19]:
def fibonacci(result, n):
    for i in range(n):
        if i>1: 
            result[i] = result[i-1]+ result[i-2]
        else:
            result[i] = 1

In [7]:
import time

In [18]:
import ctypes

In [21]:
cdll_ = ctypes.CDLL('__libC.dll')

In [25]:
cdll_.fibonacci_array(a,size)

ArgumentError: argument 1: <class 'TypeError'>: Don't know how to convert parameter 1

In [27]:
cdll_.fibonacci_array.argtypes = [np.ctypeslib.ndpointer(dtype = np.int32), ctypes.c_int]

In [28]:
cdll_.fibonacci_array.restype = None

In [30]:
cdll_.fibonacci_array(a, size)

In [31]:
a

array([ 1,  1,  2,  3,  5,  8, 13, 21, 34, 55])

In [24]:
cdll.fibonacci_array

<function uos_statphys.C_ext.functions.<locals>.fibonacci_array(result: numpy.ndarray, n: int) -> None>

In [8]:
%%timeit 
size = 1000
a= np.empty([size],dtype = np.int32)
fibonacci(a,size)

908 µs ± 20.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
%%timeit 
size = 1000
a= np.empty([size],dtype = np.int32)
cdll.fibonacci_array(a,size)

16 µs ± 351 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
np.empty([size])

array([7.88212664e-312, 1.77863633e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 4.50528535e+174, 2.10654095e-052, 6.25549781e-091,
       3.59957939e+175, 4.59174195e-315])

In [4]:
print(cdll.source)

#include <stdio.h>
#include <iostream>

//@extern_python

using namespace std;


//@python_def
int add(int a, int b){
    return a + b;
}

//@python_def
//! Short summery
//! 
void array_add(int* c, int* a, int* b, int n){
    for (size_t i = 0; i < n; i++)
    {
        c[i] = a[i] +b[i] + 1;
    }
}

//@python_def
int dot_product(int* a, int* b, int n){
    int sum = 0;
    for (size_t i = 0; i < n; i++)
    {
        sum = sum +  a[i] * b[i];
    }
    return sum;
}


장점 :  
> - c 내부 한스텝 한스텝 디버깅을 python을 이용해서 할수 있다.  
> - c 코드의 중간 결과를 확인 할수 있다.  

단점 :
> - 파이선과 혼용해서 iteration 하는 경우 속도저하가 발생한다.  


In [8]:
cdll.dot_product()

6

In [10]:
aa = np.empty([12])
cdll.array_add(aa.astype(np.int32), np.arange(12),np.arange(12),12)

In [11]:
aa

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])